### ISSUE TITLE
Should `Matrix` really be heap-allocated here?

### ISSUE THREAD

**Issue by benny-n** [IliaFeldgun/cpp-noob#2]
https://github.com/IliaFeldgun/cpp-noob/blob/01dbd16aabe106846e3bc9a19f9def34ac29343f/main.cpp#L14

Food for thought.
https://stackoverflow.com/a/79936

**Comment by IliaFeldgun** [comment]
I think the size is always dynamic (I want it to stretch fullscreen eventually), but I'll try to see if I can get it to compile without heap.

**Comment by IliaFeldgun** [comment]
In general I think it can be a struct, just too noob.

**Comment by IliaFeldgun** [comment]
Less heap more stack.
