### ISSUE TITLE
Memory leaks in `Matrix`

### ISSUE THREAD

**Issue by benny-n** [IliaFeldgun/cpp-noob#4]
https://github.com/IliaFeldgun/cpp-noob/blob/01dbd16aabe106846e3bc9a19f9def34ac29343f/matrix.cpp#L7

Who is going to free this memory?
Read about destructors:
https://learn.microsoft.com/en-us/cpp/cpp/destructors-cpp?view=msvc-170

Advanced:
Use smart pointers :)
https://learn.microsoft.com/en-us/cpp/cpp/smart-pointers-modern-cpp?view=msvc-170

**Comment by IliaFeldgun** [comment]
Basically done.
